# Generated by Django 5.0 on 2023-12-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=12)),
                ('head_dic', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=1)),
            ],
        ),
    ]
