# Generated by Django 5.0 on 2024-01-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeusers',
            options={'ordering': ('account',), 'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AlterField(
            model_name='homeusers',
            name='gender',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='homeusers',
            name='head_dic',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homeusers',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
