# Generated by Django 5.0 on 2024-01-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=12, null=True)),
                ('head_dic', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'ordering': ('account',),
            },
        ),
    ]
